apiVersion: workstations.googleapis.com/v1
kind: WorkstationConfig
metadata:
  name: app-fenix-dev
  namespace: default
spec:
  region: us-central1
  machineType: e2-standard-4
  container:
    image: us-docker.pkg.dev/cloud-workstations-images/predefined/code-oss:latest
    env:
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: "3001"
    ports:
      - containerPort: 3001
        name: "vite-dev"
  persistentDirectories:
    - mountPath: /home/user/app-fenix
      gcePd:
        sizeGb: 50
        type: pd-ssd
  startupScript:
    runAsNonRoot: true
    script: |
      #!/bin/bash
      cd /home/user/app-fenix
      npm install
      npm run dev -- --host 0.0.0.0 --port 3001 